server:
  port: 8080

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: brain_service
  sslmode: disable

llm:
  provider: openai
  api_key: "your-api-key-here"
  model: "gpt-4"
  max_tokens: 2000
  temperature: 0.7