// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: admin/v1/admin.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- REQUESTS & RESPONSES ---
type CreateTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetRequest) Reset() {
	*x = CreateTweetRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetRequest) ProtoMessage() {}

func (x *CreateTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetRequest.ProtoReflect.Descriptor instead.
func (*CreateTweetRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTweetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateTweetRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type CreateTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTweetResponse) Reset() {
	*x = CreateTweetResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTweetResponse) ProtoMessage() {}

func (x *CreateTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTweetResponse.ProtoReflect.Descriptor instead.
func (*CreateTweetResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type GetTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetRequest) Reset() {
	*x = GetTweetRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetRequest) ProtoMessage() {}

func (x *GetTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetRequest.ProtoReflect.Descriptor instead.
func (*GetTweetRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetTweetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetResponse) Reset() {
	*x = GetTweetResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetResponse) ProtoMessage() {}

func (x *GetTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetResponse.ProtoReflect.Descriptor instead.
func (*GetTweetResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type ListTweetsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthorId       string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	IsFinancial    bool                   `protobuf:"varint,2,opt,name=is_financial,json=isFinancial,proto3" json:"is_financial,omitempty"`
	SentimentLabel string                 `protobuf:"bytes,3,opt,name=sentiment_label,json=sentimentLabel,proto3" json:"sentiment_label,omitempty"`
	Symbols        []string               `protobuf:"bytes,4,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartTime      int64                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit          int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTweetsRequest) Reset() {
	*x = ListTweetsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTweetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTweetsRequest) ProtoMessage() {}

func (x *ListTweetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTweetsRequest.ProtoReflect.Descriptor instead.
func (*ListTweetsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListTweetsRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *ListTweetsRequest) GetIsFinancial() bool {
	if x != nil {
		return x.IsFinancial
	}
	return false
}

func (x *ListTweetsRequest) GetSentimentLabel() string {
	if x != nil {
		return x.SentimentLabel
	}
	return ""
}

func (x *ListTweetsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ListTweetsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ListTweetsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ListTweetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTweetsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTweetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTweetsResponse) Reset() {
	*x = ListTweetsResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTweetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTweetsResponse) ProtoMessage() {}

func (x *ListTweetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTweetsResponse.ProtoReflect.Descriptor instead.
func (*ListTweetsResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListTweetsResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

type UpdateTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Sentiment     *Sentiment             `protobuf:"bytes,3,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	Engagement    *Engagement            `protobuf:"bytes,4,opt,name=engagement,proto3" json:"engagement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTweetRequest) Reset() {
	*x = UpdateTweetRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTweetRequest) ProtoMessage() {}

func (x *UpdateTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTweetRequest.ProtoReflect.Descriptor instead.
func (*UpdateTweetRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTweetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTweetRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateTweetRequest) GetSentiment() *Sentiment {
	if x != nil {
		return x.Sentiment
	}
	return nil
}

func (x *UpdateTweetRequest) GetEngagement() *Engagement {
	if x != nil {
		return x.Engagement
	}
	return nil
}

type UpdateTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTweetResponse) Reset() {
	*x = UpdateTweetResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTweetResponse) ProtoMessage() {}

func (x *UpdateTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTweetResponse.ProtoReflect.Descriptor instead.
func (*UpdateTweetResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTweetResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

type DeleteTweetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetRequest) Reset() {
	*x = DeleteTweetRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetRequest) ProtoMessage() {}

func (x *DeleteTweetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetRequest.ProtoReflect.Descriptor instead.
func (*DeleteTweetRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTweetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTweetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTweetResponse) Reset() {
	*x = DeleteTweetResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTweetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTweetResponse) ProtoMessage() {}

func (x *DeleteTweetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTweetResponse.ProtoReflect.Descriptor instead.
func (*DeleteTweetResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

type GetTweetsBySymbolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetsBySymbolRequest) Reset() {
	*x = GetTweetsBySymbolRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetsBySymbolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsBySymbolRequest) ProtoMessage() {}

func (x *GetTweetsBySymbolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsBySymbolRequest.ProtoReflect.Descriptor instead.
func (*GetTweetsBySymbolRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetTweetsBySymbolRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetTweetsBySymbolRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTweetsBySymbolRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTweetsBySymbolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetsBySymbolResponse) Reset() {
	*x = GetTweetsBySymbolResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetsBySymbolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsBySymbolResponse) ProtoMessage() {}

func (x *GetTweetsBySymbolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsBySymbolResponse.ProtoReflect.Descriptor instead.
func (*GetTweetsBySymbolResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetTweetsBySymbolResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

type GetTweetsBySentimentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetsBySentimentRequest) Reset() {
	*x = GetTweetsBySentimentRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetsBySentimentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsBySentimentRequest) ProtoMessage() {}

func (x *GetTweetsBySentimentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsBySentimentRequest.ProtoReflect.Descriptor instead.
func (*GetTweetsBySentimentRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetTweetsBySentimentRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *GetTweetsBySentimentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTweetsBySentimentRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetTweetsBySentimentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetsBySentimentResponse) Reset() {
	*x = GetTweetsBySentimentResponse{}
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetsBySentimentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetsBySentimentResponse) ProtoMessage() {}

func (x *GetTweetsBySentimentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetsBySentimentResponse.ProtoReflect.Descriptor instead.
func (*GetTweetsBySentimentResponse) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *GetTweetsBySentimentResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

// --- ADVANCED MESSAGES ---
type Tweet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Sentiment     *Sentiment             `protobuf:"bytes,6,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	IsFinancial   bool                   `protobuf:"varint,7,opt,name=is_financial,json=isFinancial,proto3" json:"is_financial,omitempty"`
	Symbols       []string               `protobuf:"bytes,8,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Engagement    *Engagement            `protobuf:"bytes,9,opt,name=engagement,proto3" json:"engagement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *Tweet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tweet) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Tweet) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tweet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tweet) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Tweet) GetSentiment() *Sentiment {
	if x != nil {
		return x.Sentiment
	}
	return nil
}

func (x *Tweet) GetIsFinancial() bool {
	if x != nil {
		return x.IsFinancial
	}
	return false
}

func (x *Tweet) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *Tweet) GetEngagement() *Engagement {
	if x != nil {
		return x.Engagement
	}
	return nil
}

type Sentiment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         float64                `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sentiment) Reset() {
	*x = Sentiment{}
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sentiment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sentiment) ProtoMessage() {}

func (x *Sentiment) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sentiment.ProtoReflect.Descriptor instead.
func (*Sentiment) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *Sentiment) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Sentiment) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Engagement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetweetCount  int32                  `protobuf:"varint,1,opt,name=retweet_count,json=retweetCount,proto3" json:"retweet_count,omitempty"`
	FavoriteCount int32                  `protobuf:"varint,2,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	ReplyCount    int32                  `protobuf:"varint,3,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Engagement) Reset() {
	*x = Engagement{}
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Engagement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Engagement) ProtoMessage() {}

func (x *Engagement) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Engagement.ProtoReflect.Descriptor instead.
func (*Engagement) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *Engagement) GetRetweetCount() int32 {
	if x != nil {
		return x.RetweetCount
	}
	return 0
}

func (x *Engagement) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Engagement) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\badmin.v1\"E\n" +
	"\x12CreateTweetRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\"<\n" +
	"\x13CreateTweetResponse\x12%\n" +
	"\x05tweet\x18\x01 \x01(\v2\x0f.admin.v1.TweetR\x05tweet\"!\n" +
	"\x0fGetTweetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetTweetResponse\x12%\n" +
	"\x05tweet\x18\x01 \x01(\v2\x0f.admin.v1.TweetR\x05tweet\"\xfe\x01\n" +
	"\x11ListTweetsRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\x12!\n" +
	"\fis_financial\x18\x02 \x01(\bR\visFinancial\x12'\n" +
	"\x0fsentiment_label\x18\x03 \x01(\tR\x0esentimentLabel\x12\x18\n" +
	"\asymbols\x18\x04 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offset\"=\n" +
	"\x12ListTweetsResponse\x12'\n" +
	"\x06tweets\x18\x01 \x03(\v2\x0f.admin.v1.TweetR\x06tweets\"\xa1\x01\n" +
	"\x12UpdateTweetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x121\n" +
	"\tsentiment\x18\x03 \x01(\v2\x13.admin.v1.SentimentR\tsentiment\x124\n" +
	"\n" +
	"engagement\x18\x04 \x01(\v2\x14.admin.v1.EngagementR\n" +
	"engagement\"<\n" +
	"\x13UpdateTweetResponse\x12%\n" +
	"\x05tweet\x18\x01 \x01(\v2\x0f.admin.v1.TweetR\x05tweet\"$\n" +
	"\x12DeleteTweetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteTweetResponse\"`\n" +
	"\x18GetTweetsBySymbolRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"D\n" +
	"\x19GetTweetsBySymbolResponse\x12'\n" +
	"\x06tweets\x18\x01 \x03(\v2\x0f.admin.v1.TweetR\x06tweets\"a\n" +
	"\x1bGetTweetsBySentimentRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"G\n" +
	"\x1cGetTweetsBySentimentResponse\x12'\n" +
	"\x06tweets\x18\x01 \x03(\v2\x0f.admin.v1.TweetR\x06tweets\"\xac\x02\n" +
	"\x05Tweet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\x03R\tupdatedAt\x121\n" +
	"\tsentiment\x18\x06 \x01(\v2\x13.admin.v1.SentimentR\tsentiment\x12!\n" +
	"\fis_financial\x18\a \x01(\bR\visFinancial\x12\x18\n" +
	"\asymbols\x18\b \x03(\tR\asymbols\x124\n" +
	"\n" +
	"engagement\x18\t \x01(\v2\x14.admin.v1.EngagementR\n" +
	"engagement\"7\n" +
	"\tSentiment\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"y\n" +
	"\n" +
	"Engagement\x12#\n" +
	"\rretweet_count\x18\x01 \x01(\x05R\fretweetCount\x12%\n" +
	"\x0efavorite_count\x18\x02 \x01(\x05R\rfavoriteCount\x12\x1f\n" +
	"\vreply_count\x18\x03 \x01(\x05R\n" +
	"replyCount2\xd6\x04\n" +
	"\x11AdminTweetService\x12L\n" +
	"\vCreateTweet\x12\x1c.admin.v1.CreateTweetRequest\x1a\x1d.admin.v1.CreateTweetResponse\"\x00\x12C\n" +
	"\bGetTweet\x12\x19.admin.v1.GetTweetRequest\x1a\x1a.admin.v1.GetTweetResponse\"\x00\x12I\n" +
	"\n" +
	"ListTweets\x12\x1b.admin.v1.ListTweetsRequest\x1a\x1c.admin.v1.ListTweetsResponse\"\x00\x12L\n" +
	"\vUpdateTweet\x12\x1c.admin.v1.UpdateTweetRequest\x1a\x1d.admin.v1.UpdateTweetResponse\"\x00\x12L\n" +
	"\vDeleteTweet\x12\x1c.admin.v1.DeleteTweetRequest\x1a\x1d.admin.v1.DeleteTweetResponse\"\x00\x12^\n" +
	"\x11GetTweetsBySymbol\x12\".admin.v1.GetTweetsBySymbolRequest\x1a#.admin.v1.GetTweetsBySymbolResponse\"\x00\x12g\n" +
	"\x14GetTweetsBySentiment\x12%.admin.v1.GetTweetsBySentimentRequest\x1a&.admin.v1.GetTweetsBySentimentResponse\"\x00BPZNgithub.com/Denterry/FinancialAdviser/Backend/x-service/pkg/pb/admin/v1;adminpbb\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_admin_v1_admin_proto_goTypes = []any{
	(*CreateTweetRequest)(nil),           // 0: admin.v1.CreateTweetRequest
	(*CreateTweetResponse)(nil),          // 1: admin.v1.CreateTweetResponse
	(*GetTweetRequest)(nil),              // 2: admin.v1.GetTweetRequest
	(*GetTweetResponse)(nil),             // 3: admin.v1.GetTweetResponse
	(*ListTweetsRequest)(nil),            // 4: admin.v1.ListTweetsRequest
	(*ListTweetsResponse)(nil),           // 5: admin.v1.ListTweetsResponse
	(*UpdateTweetRequest)(nil),           // 6: admin.v1.UpdateTweetRequest
	(*UpdateTweetResponse)(nil),          // 7: admin.v1.UpdateTweetResponse
	(*DeleteTweetRequest)(nil),           // 8: admin.v1.DeleteTweetRequest
	(*DeleteTweetResponse)(nil),          // 9: admin.v1.DeleteTweetResponse
	(*GetTweetsBySymbolRequest)(nil),     // 10: admin.v1.GetTweetsBySymbolRequest
	(*GetTweetsBySymbolResponse)(nil),    // 11: admin.v1.GetTweetsBySymbolResponse
	(*GetTweetsBySentimentRequest)(nil),  // 12: admin.v1.GetTweetsBySentimentRequest
	(*GetTweetsBySentimentResponse)(nil), // 13: admin.v1.GetTweetsBySentimentResponse
	(*Tweet)(nil),                        // 14: admin.v1.Tweet
	(*Sentiment)(nil),                    // 15: admin.v1.Sentiment
	(*Engagement)(nil),                   // 16: admin.v1.Engagement
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	14, // 0: admin.v1.CreateTweetResponse.tweet:type_name -> admin.v1.Tweet
	14, // 1: admin.v1.GetTweetResponse.tweet:type_name -> admin.v1.Tweet
	14, // 2: admin.v1.ListTweetsResponse.tweets:type_name -> admin.v1.Tweet
	15, // 3: admin.v1.UpdateTweetRequest.sentiment:type_name -> admin.v1.Sentiment
	16, // 4: admin.v1.UpdateTweetRequest.engagement:type_name -> admin.v1.Engagement
	14, // 5: admin.v1.UpdateTweetResponse.tweet:type_name -> admin.v1.Tweet
	14, // 6: admin.v1.GetTweetsBySymbolResponse.tweets:type_name -> admin.v1.Tweet
	14, // 7: admin.v1.GetTweetsBySentimentResponse.tweets:type_name -> admin.v1.Tweet
	15, // 8: admin.v1.Tweet.sentiment:type_name -> admin.v1.Sentiment
	16, // 9: admin.v1.Tweet.engagement:type_name -> admin.v1.Engagement
	0,  // 10: admin.v1.AdminTweetService.CreateTweet:input_type -> admin.v1.CreateTweetRequest
	2,  // 11: admin.v1.AdminTweetService.GetTweet:input_type -> admin.v1.GetTweetRequest
	4,  // 12: admin.v1.AdminTweetService.ListTweets:input_type -> admin.v1.ListTweetsRequest
	6,  // 13: admin.v1.AdminTweetService.UpdateTweet:input_type -> admin.v1.UpdateTweetRequest
	8,  // 14: admin.v1.AdminTweetService.DeleteTweet:input_type -> admin.v1.DeleteTweetRequest
	10, // 15: admin.v1.AdminTweetService.GetTweetsBySymbol:input_type -> admin.v1.GetTweetsBySymbolRequest
	12, // 16: admin.v1.AdminTweetService.GetTweetsBySentiment:input_type -> admin.v1.GetTweetsBySentimentRequest
	1,  // 17: admin.v1.AdminTweetService.CreateTweet:output_type -> admin.v1.CreateTweetResponse
	3,  // 18: admin.v1.AdminTweetService.GetTweet:output_type -> admin.v1.GetTweetResponse
	5,  // 19: admin.v1.AdminTweetService.ListTweets:output_type -> admin.v1.ListTweetsResponse
	7,  // 20: admin.v1.AdminTweetService.UpdateTweet:output_type -> admin.v1.UpdateTweetResponse
	9,  // 21: admin.v1.AdminTweetService.DeleteTweet:output_type -> admin.v1.DeleteTweetResponse
	11, // 22: admin.v1.AdminTweetService.GetTweetsBySymbol:output_type -> admin.v1.GetTweetsBySymbolResponse
	13, // 23: admin.v1.AdminTweetService.GetTweetsBySentiment:output_type -> admin.v1.GetTweetsBySentimentResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
