// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tweets/v1/tweets.proto

package tweetspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- REQUESTS & RESPONSES ---
type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // query to search for
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`    // max number of tweets to ingest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_tweets_v1_tweets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_v1_tweets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_tweets_v1_tweets_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *IngestRequest) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ingested      int32                  `protobuf:"varint,1,opt,name=ingested,proto3" json:"ingested,omitempty"` // number of tweets ingested
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_tweets_v1_tweets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_v1_tweets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_tweets_v1_tweets_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetIngested() int32 {
	if x != nil {
		return x.Ingested
	}
	return 0
}

type ListLatestTweetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // max number of tweets to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestTweetsRequest) Reset() {
	*x = ListLatestTweetsRequest{}
	mi := &file_tweets_v1_tweets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestTweetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestTweetsRequest) ProtoMessage() {}

func (x *ListLatestTweetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_v1_tweets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestTweetsRequest.ProtoReflect.Descriptor instead.
func (*ListLatestTweetsRequest) Descriptor() ([]byte, []int) {
	return file_tweets_v1_tweets_proto_rawDescGZIP(), []int{2}
}

func (x *ListLatestTweetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListLatestTweetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweets        []*Tweet               `protobuf:"bytes,1,rep,name=tweets,proto3" json:"tweets,omitempty"` // list of tweets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLatestTweetsResponse) Reset() {
	*x = ListLatestTweetsResponse{}
	mi := &file_tweets_v1_tweets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLatestTweetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLatestTweetsResponse) ProtoMessage() {}

func (x *ListLatestTweetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_v1_tweets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLatestTweetsResponse.ProtoReflect.Descriptor instead.
func (*ListLatestTweetsResponse) Descriptor() ([]byte, []int) {
	return file_tweets_v1_tweets_proto_rawDescGZIP(), []int{3}
}

func (x *ListLatestTweetsResponse) GetTweets() []*Tweet {
	if x != nil {
		return x.Tweets
	}
	return nil
}

type GetTweetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // tweet id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetByIDRequest) Reset() {
	*x = GetTweetByIDRequest{}
	mi := &file_tweets_v1_tweets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByIDRequest) ProtoMessage() {}

func (x *GetTweetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_v1_tweets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTweetByIDRequest) Descriptor() ([]byte, []int) {
	return file_tweets_v1_tweets_proto_rawDescGZIP(), []int{4}
}

func (x *GetTweetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTweetByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tweet         *Tweet                 `protobuf:"bytes,1,opt,name=tweet,proto3" json:"tweet,omitempty"` // tweet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTweetByIDResponse) Reset() {
	*x = GetTweetByIDResponse{}
	mi := &file_tweets_v1_tweets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTweetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTweetByIDResponse) ProtoMessage() {}

func (x *GetTweetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_v1_tweets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTweetByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTweetByIDResponse) Descriptor() ([]byte, []int) {
	return file_tweets_v1_tweets_proto_rawDescGZIP(), []int{5}
}

func (x *GetTweetByIDResponse) GetTweet() *Tweet {
	if x != nil {
		return x.Tweet
	}
	return nil
}

// --- ADVANCED MESSAGES ---
type Tweet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Lang          string                 `protobuf:"bytes,5,opt,name=lang,proto3" json:"lang,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix seconds
	FetchedAt     int64                  `protobuf:"varint,7,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"` // unix seconds (when we stored it)
	Likes         int32                  `protobuf:"varint,8,opt,name=likes,proto3" json:"likes,omitempty"`
	Replies       int32                  `protobuf:"varint,9,opt,name=replies,proto3" json:"replies,omitempty"`
	Retweets      int32                  `protobuf:"varint,10,opt,name=retweets,proto3" json:"retweets,omitempty"`
	Views         int32                  `protobuf:"varint,11,opt,name=views,proto3" json:"views,omitempty"`
	Urls          []string               `protobuf:"bytes,12,rep,name=urls,proto3" json:"urls,omitempty"`     // list of urls
	Photos        []string               `protobuf:"bytes,13,rep,name=photos,proto3" json:"photos,omitempty"` // list of photos
	Videos        []string               `protobuf:"bytes,14,rep,name=videos,proto3" json:"videos,omitempty"` // list of videos
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tweet) Reset() {
	*x = Tweet{}
	mi := &file_tweets_v1_tweets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tweet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tweet) ProtoMessage() {}

func (x *Tweet) ProtoReflect() protoreflect.Message {
	mi := &file_tweets_v1_tweets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tweet.ProtoReflect.Descriptor instead.
func (*Tweet) Descriptor() ([]byte, []int) {
	return file_tweets_v1_tweets_proto_rawDescGZIP(), []int{6}
}

func (x *Tweet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tweet) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tweet) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Tweet) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Tweet) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *Tweet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tweet) GetFetchedAt() int64 {
	if x != nil {
		return x.FetchedAt
	}
	return 0
}

func (x *Tweet) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Tweet) GetReplies() int32 {
	if x != nil {
		return x.Replies
	}
	return 0
}

func (x *Tweet) GetRetweets() int32 {
	if x != nil {
		return x.Retweets
	}
	return 0
}

func (x *Tweet) GetViews() int32 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Tweet) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Tweet) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *Tweet) GetVideos() []string {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_tweets_v1_tweets_proto protoreflect.FileDescriptor

const file_tweets_v1_tweets_proto_rawDesc = "" +
	"\n" +
	"\x16tweets/v1/tweets.proto\x12\ttweets.v1\"7\n" +
	"\rIngestRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\",\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\bingested\x18\x01 \x01(\x05R\bingested\"/\n" +
	"\x17ListLatestTweetsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"D\n" +
	"\x18ListLatestTweetsResponse\x12(\n" +
	"\x06tweets\x18\x01 \x03(\v2\x10.tweets.v1.TweetR\x06tweets\"%\n" +
	"\x13GetTweetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x14GetTweetByIDResponse\x12&\n" +
	"\x05tweet\x18\x01 \x01(\v2\x10.tweets.v1.TweetR\x05tweet\"\xdc\x02\n" +
	"\x05Tweet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x12\n" +
	"\x04lang\x18\x05 \x01(\tR\x04lang\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"fetched_at\x18\a \x01(\x03R\tfetchedAt\x12\x14\n" +
	"\x05likes\x18\b \x01(\x05R\x05likes\x12\x18\n" +
	"\areplies\x18\t \x01(\x05R\areplies\x12\x1a\n" +
	"\bretweets\x18\n" +
	" \x01(\x05R\bretweets\x12\x14\n" +
	"\x05views\x18\v \x01(\x05R\x05views\x12\x12\n" +
	"\x04urls\x18\f \x03(\tR\x04urls\x12\x16\n" +
	"\x06photos\x18\r \x03(\tR\x06photos\x12\x16\n" +
	"\x06videos\x18\x0e \x03(\tR\x06videos2\xfb\x01\n" +
	"\fTweetService\x12=\n" +
	"\x06Ingest\x12\x18.tweets.v1.IngestRequest\x1a\x19.tweets.v1.IngestResponse\x12[\n" +
	"\x10ListLatestTweets\x12\".tweets.v1.ListLatestTweetsRequest\x1a#.tweets.v1.ListLatestTweetsResponse\x12O\n" +
	"\fGetTweetByID\x12\x1e.tweets.v1.GetTweetByIDRequest\x1a\x1f.tweets.v1.GetTweetByIDResponseBRZPgithub.com/Denterry/FinancialAdviser/Backend/x-service/pkg/pb/tweets/v1;tweetspbb\x06proto3"

var (
	file_tweets_v1_tweets_proto_rawDescOnce sync.Once
	file_tweets_v1_tweets_proto_rawDescData []byte
)

func file_tweets_v1_tweets_proto_rawDescGZIP() []byte {
	file_tweets_v1_tweets_proto_rawDescOnce.Do(func() {
		file_tweets_v1_tweets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tweets_v1_tweets_proto_rawDesc), len(file_tweets_v1_tweets_proto_rawDesc)))
	})
	return file_tweets_v1_tweets_proto_rawDescData
}

var file_tweets_v1_tweets_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tweets_v1_tweets_proto_goTypes = []any{
	(*IngestRequest)(nil),            // 0: tweets.v1.IngestRequest
	(*IngestResponse)(nil),           // 1: tweets.v1.IngestResponse
	(*ListLatestTweetsRequest)(nil),  // 2: tweets.v1.ListLatestTweetsRequest
	(*ListLatestTweetsResponse)(nil), // 3: tweets.v1.ListLatestTweetsResponse
	(*GetTweetByIDRequest)(nil),      // 4: tweets.v1.GetTweetByIDRequest
	(*GetTweetByIDResponse)(nil),     // 5: tweets.v1.GetTweetByIDResponse
	(*Tweet)(nil),                    // 6: tweets.v1.Tweet
}
var file_tweets_v1_tweets_proto_depIdxs = []int32{
	6, // 0: tweets.v1.ListLatestTweetsResponse.tweets:type_name -> tweets.v1.Tweet
	6, // 1: tweets.v1.GetTweetByIDResponse.tweet:type_name -> tweets.v1.Tweet
	0, // 2: tweets.v1.TweetService.Ingest:input_type -> tweets.v1.IngestRequest
	2, // 3: tweets.v1.TweetService.ListLatestTweets:input_type -> tweets.v1.ListLatestTweetsRequest
	4, // 4: tweets.v1.TweetService.GetTweetByID:input_type -> tweets.v1.GetTweetByIDRequest
	1, // 5: tweets.v1.TweetService.Ingest:output_type -> tweets.v1.IngestResponse
	3, // 6: tweets.v1.TweetService.ListLatestTweets:output_type -> tweets.v1.ListLatestTweetsResponse
	5, // 7: tweets.v1.TweetService.GetTweetByID:output_type -> tweets.v1.GetTweetByIDResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tweets_v1_tweets_proto_init() }
func file_tweets_v1_tweets_proto_init() {
	if File_tweets_v1_tweets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tweets_v1_tweets_proto_rawDesc), len(file_tweets_v1_tweets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tweets_v1_tweets_proto_goTypes,
		DependencyIndexes: file_tweets_v1_tweets_proto_depIdxs,
		MessageInfos:      file_tweets_v1_tweets_proto_msgTypes,
	}.Build()
	File_tweets_v1_tweets_proto = out.File
	file_tweets_v1_tweets_proto_goTypes = nil
	file_tweets_v1_tweets_proto_depIdxs = nil
}
