version: '3.8'

services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-secret-key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - auth-service
      - sub-service
      - ml-service
    networks:
      - financial-adviser-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - financial-adviser-network

networks:
  financial-adviser-network:
    external: true

volumes:
  redis_data: 