version: '3.9'

services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway-service
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "${HTTP_PORT:-8080}:8080"
      - "${GRPC_PORT:-9090}:9090"
    networks:
      - gateway_net

networks:
  gateway_net:
    driver: bridge