server:
  port: ":8080"
  read_timeout: 5s
  write_timeout: 10s

services:
  auth:
    host: "auth-service"
    port: ":50051"
  subscription:
    host: "sub-service"
    port: ":50052"
  ml:
    host: "ml-service"
    port: ":50053"

redis:
  host: "redis"
  port: ":6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  access_token_ttl: 15m
  refresh_token_ttl: 720h
  signing_method: "HS256"
  signing_key: "your-signing-key"
  verification_key: "your-verification-key"

log:
  level: "info"
  file: "logs/gateway.log" 